codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "test/**"
  - "bench/**"
  - "docs/**"
  - "**/*.g.cs"
  - "**/*.g.i.cs"
  - "**/*.Designer.cs"
  - "**/*.designer.cs"
  - "**/*AssemblyInfo.cs"
  - "**/obj/**"
  - "**/bin/**"

comment:
  layout: "reach,diff,flags,files"
